= Ministério da Justiça
= Secretaria de Assuntos Legislativos – SAL
= *Programa das Nações Unidas para o Desenvolvimento - PNUD*
:page-layout: base
include::links.adoc[]

= Levantamento de Requisitos - SISLEGIS

== 1. Introdução

== 1.1. Propósito
Este documento descritivo, elaborado pela equipe de Consultores de TI da SAL, tem por objetivo apresentar um estudo inicial de viabilidade do projeto, bem como as atividades desempenhadas referentes a especificação técnica, evidenciando o levantamento dos requisitos do sistema SISLEGIS, além de fornecer aos desenvolvedores os subsídios necessários para o desenvolvimento, implementação, testes e homologação do sistema.

== 1.2. Público Alvo
Este documento se destina aos arquitetos de software, engenheiros de software e implementadores do sistema.

== 1.3. Dados Gerais
* Nome do Projeto: Sistema de Acompanhamento Legislativo
* Sigla do Projeto: SISLEGIS
* Tipo de Projeto: Consultoria e Desenvolvimento

== 1.4. Envolvidos no Projeto
* Nome: Gabriel Carvalho de Sampaio
* E-mail: gabriel.sampaio@mj.gov.br
* Telefone: (61) 2025.3190
* Papel: Secretário de Assuntos Legislativos – Ministério da Justiça

* Nome: Sabrina Durigon Marques
* E-mail: sabrina.marques@mj.gov.br
* Telefone: (61) 2025.3114
* Papel: Chefe de Gabinete da Secretaria de Assuntos Legislativos – Ministério da Justiça

* Nome: Eduardo Spanó Junqueira de Paiva
* E-mail: eduardo.paiva@mj.gov.br
* Telefone: (61) 2025.3776
* Papel: Assessor do Secretário Executivo do Ministro da Justiça

* Nome: Christiano Guimarães Lins Santos
* E-mail: christiano.santos@mj.gov.br
* Telefone: (61) 2025.3114
* Papel: Consultor de TI e Coordenador do Projeto de Desenvolvimento do SISLEGIS - MJ

* Nome: Paulo Jerônimo
* E-mail: paulojeronimo@gmail.com
* Telefone: (61) 2025.3114
* Papel: Consultor de TI e Arquiteto de Software do Projeto de Desenvolvimento do SISLEGIS – MJ

* Nome: Aman Rathie
* E-mail: amanrathie@gmail.com
* Telefone: (61) 2025.3114
* Papel: Consultor de TI e Engenheiro de Software do Projeto de Desenvolvimento do SISLEGIS – MJ

* Nome: Raphael Augusto
* E-mail: raphaelbsb1@gmail.com
* Telefone: (61) 2025.3114
* Papel: Consultor de TI e Engenheiro de Software do Projeto de Desenvolvimento do SISLEGIS – MJ

* Nome: Guilherme Hott
* E-mail: guilhermehott@gmail.com
* Telefone: (61) 2025.3114
* Papel: Consultor de TI e Engenheiro de Software do Projeto de Desenvolvimento do SISLEGIS – MJ

* Nome: Thiago Souza Lopes
* E-mail: thiago.souza.lopes@gmail.com
* Telefone: (61) 2025.3114
* Papel: Consultor de TI e Arquiteto de Informação do Projeto de Desenvolvimento do SISLEGIS – MJ

== 1.5. Justificativa do Projeto
Automação e gerenciamento dos processos legislativos de interesse da Secretaria de Assuntos Legislativos, no momento todos os acompanhamentos são estáticos e descentralizados sendo feitos em planilhas Excel, E-mail. A automação permitirá maior eficiência e controle das pautas e processos legislativos.

== 1.6. Objetivos do Projeto
Consultoria, desenvolvimento, implantação, disponibilização de um sistema web acessado via internet que permita cadastrar, acompanhar, organizar e gerir os processos legislativos de interesse do MJ.

== 1.7. Escopo
Este documento realiza a elicitação de requisitos do SISLEGIS, visando a criação de um novo sistema de gestão do processo legislativo, provendo o cadastro e acompanhamento dos pareceres, notas, notas técnicas e proposições em tramitação na Câmara dos Deputados, Senado Federal e Congresso Nacional, integrando e consolidando ações e procedimentos realizados pelos Ministérios e Ministério da Justiça, de modo ágil e proficiente.

== 1.8. Premissas
Todo o desenvolvimento será estruturado em software livre ou Open Source, utilizando a plataforma Java.


== 2. Visão Geral do Produto

Criação de um novo sistema de gestão do processo legislativo, que permita o cadastro e acompanhamento dos pareceres, notas, notas técnicas e proposições em tramitação na Câmara dos Deputados, Senado Federal e Congresso Nacional, integrando e consolidando ações e procedimentos realizados pelos Ministérios e Ministério da Justiça, de modo ágil e proficiente.


== 2.1. Cenário Atual
Atualmente é utilizado pela SAL dois sistemas: EDENS e SISLEGIS (Atual).
O Sistema Edens encontra-se em desuso pela secretária, e o contrato com a empresa responsável pela manutenção foi cancelado.

Os motivos para não utilização do EDENS são:
* Grande número de funcionalidades desnecessárias;
* Interfaces complicadas;
* Problemas de integração com o MJDOC;
* Impossibilidade de anexação de arquivos;
* Problemas na verificação dos nomes dos Projetos de Leis importados, gerando duplicidade;
* Impossibilidade no acompanhamento de tarefas;
* Falta de funcionalidades importantes para a SAL.

O atual Sistema SisLegis atende em partes os interesses da Secretaria de Assuntos Legislativos. Sua principal funcionalidade é a Pauta Semanal, todavia necessita de profundas melhorias. Outro agravante é o consumo de informações, uma vez que são coletadas apenas as informações oriundas da Câmara, faltando um "push" das informações do Senado.   

Em virtude da insuficiência dos dois Sistemas, é frequente entre as áreas:
* Grande número de troca de e-mails;
* Geração de planilhas em Excel para controle interno;
* Produção manual de documentos;
* Compartilhamento de arquivos na rede sem backup
* Perda de informações.

== 2.2. Descrição dos usuários 
* Chefe de Gabinete;
* Secretário de Assuntos Legislativos;
* Advogados;
* Coordenadores;
* Assessores;
* Equipe de apoio dos coordenadores.


== 3. Requisitos Funcionais
* Manter Usuário
** Anexar currículos da equipe;
** Gerenciar perfil usuário;
** Integração via LDAP.

* Manter Tipos de Proposição

* Manter Tratamentos de Proposição

* Manter Proposição
** Incluir número do protocolo MJDOC e contemplar SEI;
** Consumir dados das duas casas legislativas;
** Acessar trâmites das proposições nas duas casas legislativas e posicionamentos dos ministérios;
** Atrelar registro de manifestações, comentários e documentos administrativos relacionados;
** Priorização das Proposições para reunião de Pauta;
** Anexar arquivo;

* Manter Exposições de Motivos
** *Internas (de autoria do MJ)*:
*** Anexar notas elaboradas;
*** Associar EMI’s arquivadas sobre o mesmo tema;
*** Relacionar a EMI com o PL e norma originada.
 
** *Externo (de autoria de outros órgãos em coautoria com o MJ)*:
*** Anexar texto das EMI's recebidas via SIDOF;
*** Juntar notas elaboradas;
*** Anexar documentos administrativos relacionados;
*** Classificar EMI’s.

* Manter Manifestação
** Notas;
** Notas técnicas;
** Pareceres de Sanção;
** Manter demandas dos Parlamentares;
** Posicionamentos preliminares;
** Anexar textos das manifestações;
** Vincular documento de Manifestação.

* Manter Contatos da Secretária
** Agendar compromissos.
** Possibilitar a associação e unificação de contatos em duplicidade.
** Permitir fácil usabilidade e interface amigável focada na secretária.

* Realizar controle de distribuição de demandas e prazos para resposta
** Anexar arquivos e notificações no módulo de tarefas;
** Filtro de destinatários;
** Notificação via e-mail;
** Priorização de tarefas;
** Possibilitar o usuário verificar suas tarefas;
** Viabilizar a geração em mais de um formato de arquivo;
** Gerar relatórios referentes à distribuição das demandas, responsáveis e prazos;
** Manter demanda de parlamentares;
** Requerimento Informativo;
** Criar alerta quando o prazo de Requerimento estiver próximo.

* Consultar Documentos - SEI
** Ofícios;
** Memorandos;
** Despachos.

* Montar Pauta Semanal
** Consultar proposições da Câmara dos Deputados e Senado Federal;
** Vincular as tramitações das Casas;
** Agenda Legislativa: Relatório Semanal de todas as proposições, editável;
** Evidenciar os posicionamentos ministeriais e os acontecidos oriundos da SAL.

* Categorizar (tags) conteúdo:
** Proposições;
** Manifestações;
** Exposição de Motivos (EM).

* Pesquisas por:
** Forma livre, pesquisando todo conteúdo do portal;
** Conteúdo dentro dos Documentos;
** Indexar temas por termos autorizados;
** Categorias.

* Incluir dados do processo - SEI.

* Consulta e verificação dos dados existentes no Banco de Dados do EDENS que serão salvos no novo sistema SISLEGIS;

* Notificações de alterações de texto ou tramitações nos Projetos de Lei.

* Manter Portarias - Referência
** Pesquisa de Portarias para o público externo
** Migração de dados de Portarias do sistema atual para o sistema a ser desenvolvido.

* Mecanismo de notificação automática na medida em que mudanças nas proposições prioritárias ou já inclusas no sistema apareçam nas pautas da Câmara dos Deputados, Senado Federal e Congresso Nacional. 


== 4. Requisitos Não Funcionais

* Segurança: O Sistema terá um procedimento de autorização de usuários, nos quais terão que se identificar usando um (login) e uma senha. Somente usuários autorizados terão acesso aos dados.

* Desempenho: Os requisitos de performance deverão ser explicitados em documento de arquitetura.

* Usabilidade: Deverão ser utilizados novos padrões de usabilidade e interface amigáveis.

* Confiabilidade: O Sistema deverá ficar disponível 24 (Vinte e Quatro) horas por dia durante 07 (Sete) dias da semana, durante todo o ano. As paradas para manutenção de qualquer espécie neste período deverão ser negociadas com a SAL e quando necessárias devem acontecer fora do horário comercial.

* Padrões Aplicáveis: O Sistema será desenvolvido na Plataforma Java. Maiores detalhes sobre a codificação do sistema estarão contemplados no documento de arquitetura.

* Hardware: Desktop e Notebook. Tablet e Mobile será feito estudo de viabilidade.

* Documentação: Os artefatos produzidos estarão em conformidade com as melhores práticas. As adaptações poderão ser realizadas nos modelos da documentação, caso necessárias.

* O Sistema será homologado pelos seguintes browsers: Mozilla Firefox e Google Chrome.


== 5. Glossário

[glossary]
EMI:: - Exposição de Motivos Interministerial

PL:: - Projeto de Lei

SAL:: - Secretária de Assunto Legislativo

SIDOF:: - Sistema de Geração e Tramitação de Documentos

ASPAR:: - Assessoria Parlamentar

Requerimento:: - Proposição de alguma providência

Proposição:: - Toda matéria sujeita à aprovação do Plenário da Assembleia

Manifestação:: - Resposta à uma proposição ou requerimento 





// vim: set syntax=asciidoc:
